### ISSUE TITLE
Invent tabbing for PMs

### ISSUE THREAD

**Issue by Darkov3** [Darkov3/forum-project#45]

**Comment by Inqy** [comment]
`USE [DB_A13363_ForumDatabaseTest]
GO

/****** Object:  Table [dbo].[ChatRoom_Users] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OpenChatRoom_Users](
	[ChatRoomId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_OpenChatRoom_Users] PRIMARY KEY CLUSTERED 
(
	[ChatRoomId] ASC,
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_OpenChatRoom_Users] UNIQUE NONCLUSTERED 
(
	[ChatRoomId] ASC,
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[OpenChatRoom_Users]  WITH CHECK ADD  CONSTRAINT [FK_OpenChatRoom_Users_ChatRooms] FOREIGN KEY([ChatRoomId])
REFERENCES [dbo].[ChatRooms] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[OpenChatRoom_Users] CHECK CONSTRAINT [FK_OpenChatRoom_Users_ChatRooms]
GO

ALTER TABLE [dbo].[OpenChatRoom_Users]  WITH CHECK ADD  CONSTRAINT [FK_OpenChatRoom_Users_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[OpenChatRoom_Users] CHECK CONSTRAINT [FK_OpenChatRoom_Users_Users]
GO`
